#Build node image from Node Docker Hub
FROM node:alpine3.10

#Make app directory in container
RUN mkdir /app

#Identify working directory
WORKDIR /app

#Copy package
COPY package.json /app

#Install npm packages from package.json
RUN npm install

#Copy over app to app folder
COPY . /app 

# Build app
RUN ["npm", "run", "build"]

#Expose server at port ( accessible outside of container)
EXPOSE 8080

#Start app 
CMD ["npm", "start"]